name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/nginx-test

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/nginx-test

      - name: Docker Pull and run from Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_DNS}}
          username: ubuntu
          key: ${{secrets.AWS_PK}}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/nginx-test
            sudo docker stop nginx-test
            sudo docker rm nginx-test
            sudo docker run nginx-test
