name: pipeline dev

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    environment: DEV

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install -g

      #      - name: Run test
      #        run: npm test

      - name: Install Eslint
        run: npm install eslint -g

      - name: Run lint
        run: npm lint

      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/nginx-test

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/nginx-test

  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Docker Pull and run from Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_DNS}}
          username: ubuntu
          key: ${{secrets.AWS_PK}}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/nginx-test
            sudo docker stop app-test
            sudo docker rm app-test
            sudo docker run --detach -p 3000:3000 --name app-test ${{secrets.DOCKER_USERNAME}}/nginx-test
