name: pipeline develop branch

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: DEV

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build

      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/app-test

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/app-test

  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Docker Pull and run from Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_DNS}}
          username: ubuntu
          key: ${{secrets.AWS_PK}}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/app-test
            sudo docker stop app-test
            sudo docker rm app-test
            sudo docker run --detach -p 3000:3000 --name app-test ${{secrets.DOCKER_USERNAME}}/app-test
